### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tancheng** [tancheng/mlir-cgra#1]
- [ ] Enable launch in the hierarchical structure (e.g., nested-loops).
- [ ] Enable pattern matching with pre-defined CGRA ops.
- [ ] Try out CONV tiling (in CNN models) and decide whether to implement it as GEMM.
- [ ] Implement integration test (on CPU).
- [ ] Enable a simple tiling strategy with the consideration of on-chip buffer size, double buffering, and DMA Gb/s.
- [ ] Determine the target models.
